/**
 * The running window's icon, in the user's theme.
 *
 * WHAT CAN AND CANNOT FOLLOW A THEME, because the distinction is the whole
 * design here. The `.ico` compiled into the executable is read by the Windows
 * shell — for the Start Menu entry, the installer, the file on disk, and the
 * taskbar button of an app that is not running — long before any of this code
 * executes, and nothing may rewrite an installed binary. That icon is fixed at
 * the Founder's palette forever.
 *
 * `BrowserWindow.setIcon` is the part that can change. It governs the title
 * bar, the task switcher and the taskbar button of a RUNNING window. So the
 * binary wears the default mark and the running app wears the user's, which is
 * the most that is true rather than the most that could be promised.
 *
 * The PNGs are generated by `npm run icons` from the same two SVGs as the
 * binary's icon, coloured from the real values in tokens.css and themes.css.
 * They ship as `extraResources`, NOT inside the asar: `nativeImage` reads a
 * path from disk, and a path inside an archive is not one.
 */
import { app, nativeImage, type BrowserWindow } from 'electron'
import { join } from 'node:path'
import { existsSync } from 'node:fs'
import { DEFAULT_THEME, type ThemeId } from '../shared/themes.js'

/**
 * Packaged: `resources/icons/`. Unpackaged: straight out of `build/themed/`,
 * so `npm run dev` shows the same thing without a build step in between.
 */
function iconPath(theme: ThemeId): string {
  const dir = app.isPackaged
    ? join(process.resourcesPath, 'icons')
    : join(__dirname, '../../build/themed')
  return join(dir, `${theme}.png`)
}

/**
 * Point the window at the icon for `theme`.
 *
 * Every failure is silence and the previous icon stays. A missing file means a
 * theme was added without re-running `npm run icons`, and the correct response
 * to that is the wrong-coloured icon a user will never notice, not a crash on
 * a settings change or an error dialog about a picture.
 */
export function applyWindowIcon(win: BrowserWindow | null, theme: ThemeId): void {
  if (!win || win.isDestroyed()) return
  const path = iconPath(theme)
  const file = existsSync(path) ? path : iconPath(DEFAULT_THEME)
  if (!existsSync(file)) return
  const image = nativeImage.createFromPath(file)
  // An unreadable or zero-byte PNG decodes to an empty image, and setting one
  // clears the icon rather than leaving it — worse than doing nothing.
  if (image.isEmpty()) return
  win.setIcon(image)
}
